/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8efd8408-5040-49e5-8d37-50b5d1abab76",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_dRW5epUw8",
    "aws_user_pools_web_client_id": "61ds97tvnjckccsthbrjq14ngl",
    "oauth": {},
    "aws_bots": "enable",
    "aws_bots_config": [
        {
            "name": "HalifaxFoodie",
            "alias": "$LATEST",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
